server:
  port: 80
spring:
  application:
    name: microservice-consumer-with-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
