server:
  #服务端口
  port: 8762
spring:
  application:
    name: spring-cloud-eureka-server-zone-02
  security:
    user:
      name: test
      password: test123
eureka:
  instance:
    hostname: localhost
    #prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: icypt
    availability-zones:
      icypt: zone-02,zone-01
    prefer-same-zone-eureka: true
    healthcheck:
      #启动健康检查，启动后如果应用状态非"up"状态，其他应用将不会发交易到此应用
      enabled: true
    #为客户端提供的注册中心的地址
    serviceUrl:
      zone-01: http://user:test123@${eureka.instance.hostname}:8761/eureka/
      zone-02: http://user:test123@${eureka.instance.hostname}:8762/eureka/