---
spring:
  profiles: peer1
  application:
      name: microservice-discovery-eureka-ha
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
server:
  port: 8761

---
spring:
  profiles: peer2
  application:
      name: microservice-discovery-eureka-ha
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
server:
  port: 8762

---
spring:
  profiles: peer3
  application:
      name: microservice-discovery-eureka-ha
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
server:
  port: 8763





