server:
  port: 6900
spring:
  application:
    name: microservice-consumer-blog-ribbon-without-eureka
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
ribbon:
  eureka:
    #如果没有依赖eureka客户端则不需要使用此配置
    enabled: false
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900