server:
  port: 8900
spring:
  application:
    name: microservice-consumer-blog-feign-with-hystrix-hystrix-factory
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
logging:
  level:
    com.icypt.learn.feign.UserFeignClient: debug

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
         # 暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
         #http://localhost:7900/actuator/metrics
         #http://localhost:7900/actuator/metrics/jvm.memory.max
        include: '*'
feign:
  hystrix:
    enabled: true