server:
  port: 80
spring:
  application:
    name: microservice-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"
service:
  url: http://microservice-nacos-provider
feign:
  sentinel:
    enabled: true
