server:
  port: 5900
spring:
  application:
    #应用名称
    name: microservice-getway-zuul
  security:
    user:
      name: user
      password: password123
eureka:
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
      service-url:
        defaultZone: http://user:password123@localhost:8761/eureka/
#zuul:
#  prefix: /user
#  #剥去要访问的微服务serviceid
#  strip-prefix: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 120000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 120000

logging:
  level:
    com.netflix: debug

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
         # 暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
         #http://localhost:7900/actuator/metrics
         #http://localhost:7900/actuator/metrics/jvm.memory.max
        include: '*'

