server:
  port: 9527
spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #启动微服务名称进行动态路由
          enabled: true
      routes:
        - id: payment_01 #路由的ID，没有固定规则但要求唯一
#          uri: http://localhost:8002 #匹配提供服务的地址
          uri: lb://microservice-provider-register-multiple
          predicates:
            - Path=/payment/get/** #断言，路径相匹配进行路由

        - id: payment_02 #路由的ID，没有固定规则但要求唯一
#          uri: http://localhost:8002 #匹配提供服务的地址
          uri: lb://microservice-provider-register-multiple
          predicates:
            - Path=/payment/create #断言，路径相匹配进行路由

eureka:
  client:
    register-with-eureka: true
    #是否存EurekaServer同步已有的注册信息，单节点无所谓，集群情况下必须设置为true才能配合ribbon进行负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
