server:
  port: 7001
eureka:
  instance:
#    hostname: localhost #eureka服务端的实例名称
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示不需要去检索服务
    fetch-registry: false
    #注册中心提供给客户端的注册地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  server:
    #关闭自我保护机制，生产环境不建议
    enable-self-preservation: false
spring:
  application:
    name: microservice-eureka-self-protect