#携带server.servlet.context-path的时候turbine配置
server:
  port: 8040
spring:
  application:
    name: microservice-hystrix-turbine-extends
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
turbine:
  aggregator:
    cluster-config: MICROSERVICE-CONSUMER-BLOG-RIBBON-WITH-HYSTRIX-EXTENDS
  app-config: microservice-consumer-blog-ribbon-with-hystrix-extends





