server:
  port: 9002
spring:
  application:
    name: microservice-seata-order
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123580
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

mybatis:
  mapper-locations: classpath:/mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
