server:
  port: 8001
spring:
  application:
    name: microservice-provider-with-zookeeper
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_learn?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123580
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    zookeeper:
      connect-string: 192.168.31.20:2181


mybatis:
  mapper-locations: classpath:/mapper/*.xml
