server:
  port: 5900
spring:
  application:
    #应用名称
    name: microservice-getway-zuul-reg-exp
  security:
    user:
      name: user
      password: password123
eureka:
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
      service-url:
        defaultZone: http://user:password123@localhost:8761/eureka/


