server:
  port: 8080
spring:
  application:
    name: spring-cloud-eureka-client
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/