server:
  port: 8761
spring:
  application:
    #应用名称
    name: microservice-discovery-eureka
  security:
    user:
      name: user
      password: password123
eureka:
  #没有提示
  environment: product
  datacenter: cloud
  client:
    #不用eureka进行注册
    register-with-eureka: false
    #客户端不拉取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  server:
    #关闭eureka自我保护模式，生产环境不能关闭
    #enableSelfPreservation: false
    #eviction-interval-timer-in-ms: 4000





