server:
  port: 5900
spring:
  application:
    #应用名称
    name: microservice-getway-zuul-filter
  security:
    user:
      name: user
      password: password123
eureka:
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
      service-url:
        defaultZone: http://user:password123@localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
         # 暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
         #http://localhost:7900/actuator/metrics
         #http://localhost:7900/actuator/metrics/jvm.memory.max
        include: '*'

