server:
  port: 8900
spring:
  application:
    name: microservice-consumer-blog-feign
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
logging:
  level:
    com.icypt.learn.feign.UserFeignClient: debug